#!/usr/bin/env python3
"""
Environment setup script for Intelligent Chat Interface
This script helps users set up their .env file securely
"""

import os
import getpass
from pathlib import Path


def setup_environment():
    """Interactive setup for environment variables"""
    print("🔧 Intelligent Chat Interface - Environment Setup")
    print("=" * 50)
    print("This script will help you set up your .env file securely.")
    print("Your API keys will be stored locally and never shared.\n")

    # Check if .env already exists
    env_file = Path(".env")
    if env_file.exists():
        print("⚠️  .env file already exists!")
        overwrite = input("Do you want to overwrite it? (y/N): ").lower().strip()
        if overwrite != "y":
            print("Setup cancelled.")
            return

    # Collect API keys
    env_vars = {}

    print("\n📝 API Key Configuration")
    print("-" * 30)

    # OpenAI API Key (Required)
    print("\n1. OpenAI API Key (Required for AI features)")
    print("   Get your key from: https://platform.openai.com/api-keys")
    openai_key = getpass.getpass("   Enter your OpenAI API key: ").strip()
    if openai_key:
        env_vars["OPENAI_API_KEY"] = openai_key
    else:
        env_vars["OPENAI_API_KEY"] = "your_openai_api_key_here"

    # LinkedIn credentials (Optional)
    print("\n2. LinkedIn Credentials (Optional)")
    print("   Used for direct LinkedIn profile access")
    linkedin_email = input("   Enter LinkedIn email (optional): ").strip()
    if linkedin_email:
        env_vars["LINKEDIN_EMAIL"] = linkedin_email
        linkedin_password = getpass.getpass(
            "   Enter LinkedIn password (optional): "
        ).strip()
        if linkedin_password:
            env_vars["LINKEDIN_PASSWORD"] = linkedin_password
        else:
            env_vars["LINKEDIN_PASSWORD"] = "your_linkedin_password"
    else:
        env_vars["LINKEDIN_EMAIL"] = "your_linkedin_email@example.com"
        env_vars["LINKEDIN_PASSWORD"] = "your_linkedin_password"

    # SerpAPI Key (Optional)
    print("\n3. SerpAPI Key (Optional)")
    print("   Get your key from: https://serpapi.com/")
    serpapi_key = input("   Enter SerpAPI key (optional): ").strip()
    if serpapi_key:
        env_vars["SERPAPI_KEY"] = serpapi_key
    else:
        env_vars["SERPAPI_KEY"] = "your_serpapi_key_here"

    # Write .env file
    print("\n💾 Writing .env file...")
    try:
        with open(".env", "w") as f:
            f.write("# Intelligent Chat Interface - Environment Variables\n")
            f.write("# Generated by setup_env.py\n\n")

            f.write("# OpenAI API Configuration\n")
            f.write(f"OPENAI_API_KEY={env_vars['OPENAI_API_KEY']}\n\n")

            f.write("# LinkedIn API Configuration (Optional)\n")
            f.write(f"LINKEDIN_EMAIL={env_vars['LINKEDIN_EMAIL']}\n")
            f.write(f"LINKEDIN_PASSWORD={env_vars['LINKEDIN_PASSWORD']}\n\n")

            f.write("# SerpAPI Configuration (Optional)\n")
            f.write(f"SERPAPI_KEY={env_vars['SERPAPI_KEY']}\n\n")

            f.write("# Application Configuration\n")
            f.write("APP_TITLE=Intelligent Chat Interface\n")
            f.write("APP_VERSION=1.0.0\n")

        print("✅ .env file created successfully!")

        # Verify the setup
        print("\n🔍 Verifying configuration...")
        try:
            from dotenv import load_dotenv

            load_dotenv()
            openai_key = os.getenv("OPENAI_API_KEY")
            if openai_key and openai_key != "your_openai_api_key_here":
                print("✅ OpenAI API key loaded successfully")
            else:
                print("⚠️  OpenAI API key not set or using placeholder")

            print("✅ Environment configuration complete!")
            print("\n🚀 You can now run the application:")
            print("   streamlit run app.py")

        except ImportError:
            print(
                "⚠️  python-dotenv not installed. Install with: pip install python-dotenv"
            )

    except Exception as e:
        print(f"❌ Error creating .env file: {e}")


if __name__ == "__main__":
    setup_environment()
